export enum JobDuration {
  LESS_THAN_1_MONTH = 'LESS_THAN_1_MONTH',
  ONE_TO_THREE_MONTHS = 'ONE_TO_THREE_MONTHS',
  THREE_TO_SIX_MONTHS = 'THREE_TO_SIX_MONTHS',
  MORE_THAN_SIX_MONTHS = 'MORE_THAN_SIX_MONTHS',
}
