/** Spec §19.22. */
export enum TransactionType {
  ESCROW_FUND = 'ESCROW_FUND',
  ESCROW_RELEASE = 'ESCROW_RELEASE',
  HOURLY_CHARGE = 'HOURLY_CHARGE',
  CATALOG_ORDER = 'CATALOG_ORDER',
  REFUND = 'REFUND',
  PARTIAL_REFUND = 'PARTIAL_REFUND',
  WITHDRAWAL = 'WITHDRAWAL',
  COMMISSION = 'COMMISSION',
}
